version: '3'
services:
  backend:
    build:
      context: ./WeakLinkGame
      dockerfile: ./WeakLinkGame.API/Dockerfile
    container_name: weak-link-back
    volumes:
      - ./db:/app/db/
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
    ports:
      - '7089:7089'
    restart: unless-stopped

  frontend:
    build:
      context: ./www
      dockerfile: ./Dockerfile
      args:
        - SERVER_HOST=/
        - SERVER_PORT=7089
    container_name: weak-link-front
    ports:
      - '80:80'
    restart: unless-stopped
